import { addPage } from "@canva/design";
export const templateThreeGenerate = async () => {
  await addPage({
    elements: [
      {
        type: "image",
        altText: {
          text: "Property Image",
          decorative: false,
        },
        top: 0,
        left: 0,
        height: 250,
        width: 380,
        dataUrl: "${photo1}",
      },
      {
        type: "text",
        children: ["${selectedProperty.address.suburb}"],
        fontRef: "${headingFontRef}",
        color: "${brandConfiguration.brandColor}",
        top: 15,
        left: 400,
        fontSize: 18,
        fontWeight: "semibold",
        width: 300,
        textAlign: "start",
      },
      {
        type: "image",
        altText: {
          text: "Logo Image",
          decorative: false,
        },
        dataUrl: "${logo}",
        top: 15,
        left: 700,
        height: 30,
        width: 250,
      },
      {
        type: "text",
        children: ["${selectedProperty.address.streetNo} ${selectedProperty.address.streetName} ${selectedProperty.address.streetType}"],
        fontRef: "${headingFontRef}",
        color: "${brandConfiguration.brandColor}",
        top: 42,
        left: 400,
        fontSize: 12,
        width: 300,
        textAlign: "start",
      },
      {
        type: "group",
        top: 80,
        left: 400,
        width: 120,
        height: "auto",
        children: [
          {
            type: "text",
            fontRef: "${headingFontRef}",
            color: "${brandConfiguration.brandColor}",
            children: ["${selectedProperty.bed}"],
            top: 0,
            left: 0,
            fontSize: 12,
            textAlign: "start",
          },
          {
            type: "image",
            top: 0,
            left: 8,
            altText: { text: "bed icon", decorative: false },
            dataUrl: "${bedroomIcon}",
            height: 15,
            width: 15,
          },
          {
            type: "text",
            fontRef: "${headingFontRef}",
            color: "${brandConfiguration.brandColor}",
            children: ["${selectedProperty.bath}"],
            top: 0,
            left: 30,
            fontSize: 12,
            textAlign: "start",
          },
          {
            type: "image",
            top: 0,
            left: 38,
            altText: { text: "bath icon", decorative: false },
            dataUrl: "${bathroomIcon}",
            height: 15,
            width: 15,
          },
          {
            type: "text",
            fontRef: "${headingFontRef}",
            color: "${brandConfiguration.brandColor}",
            children: ["${selectedProperty.car}"],
            top: 0,
            left: 60,
            fontSize: 12,
            textAlign: "start",
          },
          {
            type: "image",
            top: 0,
            left: 68,
            altText: { text: "car icon", decorative: false },
            dataUrl: "${parkingIcon}",
            height: 15,
            width: 15,
          },
        ],
      },
      {
        type: "group",
        top: 130,
        left: 400,
        width: 300,
        height: 70,
        children: [
          {
            top: 10,
            left: 0,
            type: "shape",
            paths: [
              {
                d: "M 0 0 H 720 V 720 H 0 L 0 0",
                fill: {
                  color: "#ffffff",
                },
              },
            ],
            width: 300,
            height: 50,
            viewBox: {
              top: 0,
              left: 0,
              width: 300,
              height: 50,
            },
          },
          {
            type: "image",
            altText: {
              text: "Agent Image",
              decorative: false,
            },
            top: 0,
            left: 10,
            height: 70,
            width: 70,
            dataUrl: "${primaryAgentPhoto}",
          },
          {
            type: "text",
            fontRef: "${headingFontRef}",
            color: "${brandConfiguration.brandColor}",
            children: ["${primaryAgent.name.firstName} ${primaryAgent.name.lastName}"],
            top: 25,
            left: 100,
            fontSize: 10,
            fontWeight: "bold",
            width: 150,
            textAlign: "start",
          },
          {
            type: "text",
            fontRef: "${headingFontRef}",
            color: "${brandConfiguration.brandColor}",
            children: ["${primaryAgent.cell}"],
            top: 37,
            left: 100,
            fontSize: 8,
            width: 150,
            textAlign: "start",
          },
        ],
      },
      {
        type: "group",
        top: 212,
        left: 400,
        width: 120,
        height: 25,
        children: [
          {
            top: 0,
            left: 0,
            width: 120,
            height: 25,
            type: "shape",
            paths: [
              {
                d: "M 12.5 0 H 107.5 A 12.5 12.5 0 0 1 120 12.5 V 12.5 A 12.5 12.5 0 0 1 107.5 25 H 12.5 A 12.5 12.5 0 0 1 0 12.5 V 12.5 A 12.5 12.5 0 0 1 12.5 0 Z",
                fill: {
                  color: "${brandConfiguration.canvasBgColor}",
                },
              },
            ],
            viewBox: {
              top: 0,
              left: 0,
              width: 120,
              height: 25,
            },
          },
          {
            type: "text",
            fontRef: "${bodyFontRef}",
            color: "${brandConfiguration.fontColor}",
            children: ["Enquire Now"],
            top: 6,
            left: 0,
            fontSize: 12,
            width: 120,
            textAlign: "center",
          },
        ],
      },
    ],
  });
};
